services:
  - type: web
    name: backend
    env: node
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh && npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer